---
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: docker
    # We use this file to load the last known good version of the image
    directory: src/ansible_navigator/data/
    schedule:
      interval: daily
    labels:
      - dependencies
      - skip-changelog
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - skip-changelog
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 2
    allow:
      # Only important dependencies, for the rest we do it manually and in
      # bulk, via `tox -e deps`
      - dependency-name: ansible-*
      - dependency-name: jinja2
      - dependency-name: jsonschema
      - dependency-name: onigurumacffi
      - dependency-name: packaging
      - dependency-name: pytest
      - dependency-name: pyyaml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - skip-changelog
