# https://docs.readthedocs.io/en/stable/config-file/v2.html
---
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - pip install '.[docs]'
      - ansible-navigator --version
formats: all

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true
