- hosts: localhost
  gather_facts: False
  tasks:
  - debug:
      msg: hi

- hosts: localhost
  gather_facts: False
  tasks:
  - debug:
      msg: hi

- hosts: localhost
  gather_facts: False
  tasks:
  - debug:
      msg: hi
  - pause:
      seconds: 3
  - debug:
      var: ansible_forks


