---
- name: timezone
  hosts: all
  gather_facts: true
  vars:
    tz: Asia/Tokyo

  tasks:
    - name: "Set the timezone {{ tz }}"
      community.general.timezone:
        name: "{{ tz }}"
      failed_when: false
