---
requires_ansible: '>=2.9.10,<2.11'
plugin_routing:
  modules:
    net_banner:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_interface:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_l2_interface:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_l3_interface:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_linkagg:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_lldp:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_lldp_interface:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_logging:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_static_route:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_system:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_user:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_vlan:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
    net_vrf:
      deprecation:
        removal_date: '2022-06-01'
        warning_text: See the plugin documentation for more details
