---
name: Bug report
description: Create a report to help us improve

body:
- type: markdown
  attributes:
    value: >
      **Thank you for wanting to report a bug in ansible-navigator!**

- type: textarea
  attributes:
    label: Summary
    description: Explain the problem briefly below.
    placeholder: >-
      When I try to do X with ansible-navigator from the main branch on GitHub, Y
      breaks in a way Z under the env E. Here are all the details I know
      about this problem...
  validations:
    required: true

- type: textarea
  attributes:
    label: Ansible-navigator Version
    description: >-
      Paste verbatim output from `ansible-navigator --version` below, under
      the prompt line.
    render: console
    value: |
      $ ansible-navigator --version
    placeholder: |
      $ ansible-navigator --version
      ansible-navigator 0.7.0
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce.
    description: |
      Describe exactly how to reproduce the problem, using a minimal test-case.
      It would *really* help us understand your problem if you could also pased any playbooks,
      configs and commands you used. Also paste command and the output used to run
      ansible-navigator, under the prompt line. Leave blank if not relevant to the issue.

      **HINT:** You can paste https://gist.github.com links for larger files.

- type: textarea
  attributes:
    label: Expected Results.
    description: >-
      Describe what you expected to happen when running the steps above.
      Leave blank if not relevant to the issue.
    placeholder: >-
      I expected X to happen because I assumed Y and was shocked
      that it did not.

- type: textarea
  attributes:
    label: Actual Results
    description: |
      Describe what actually happened. Leave blank if not relevant to the issue.
      Leave blank if not relevant to the issue.
    render: console
  
- type: textarea
  attributes:
    label: Settings
    description: >-
      Paste verbatim output from `ansible-navigator.yaml` file or
      any other custom setting file defined by `ANSIBLE_NAVIGATOR_CONFIG`
      enviornment variable below (if present), under the prompt line.
      Leave blank if not relevant to the issue.
    render: console
    value: |
      $ cat ansible-navigator.yaml
    placeholder: |
      $ cat ansible-navigator.yaml
      ansible-navigator:
        logging:
          level: debug
          file: ansible-navigator.log  

- type: textarea
  attributes:
    label: Ansible navigator logs
    description: >-
      Paste verbatim relevant logs from the ansible-navigator
      log file preferably after setting the log-level to `debug`,
       under the prompt line. Leave blank if not relevant to the issue.
      **HINT:** You can paste https://gist.github.com links for larger files.
    render: console
    value: |
      $ cat ./ansible-navigator.log

- type: textarea
  attributes:
    label: Ansible Version (if running without execution environment)
    description: >-
      If running ansible on host machine (without execution environment)
      paste verbatim output from `ansible --version` below, under
      the prompt line.  Leave blank if not relevant to the issue.
    render: console
    value: |
      $ ansible --version

- type: textarea
  attributes:
    label: Execution environment details (if running with execution environment enabled)
    description: >-
      If using execution-environment with ansible-navigator
      paste the details about execution-environment that can help
      in debugging the issue. You can use command
      `ansible-navigator images <name-of-container-image>` to introspect
      execution environment.  Leave blank if not relevant to the issue.
    render: console
 
- type: textarea
  attributes:
    label: OS / Environment
    description: >-
      Provide all relevant information below, e.g. target OS versions,
      network device firmware, etc. Leave blank if not relevant to the issue.
    placeholder: RHEL 8, CentOS Stream etc.
