---
name: Documentation Report
description: Ask us about docs

body:
- type: markdown
  attributes:
    value: >
      **Thank you for wanting to report a problem with ansible-navigator
      documentation!**

- type: textarea
  attributes:
    label: Summary
    description: >
      Explain the problem briefly below, add suggestions to wording
      or structure.
    placeholder: >-
      I was reading the ansible-navigator documentation and I'm having
      problems understanding Y. It would be very helpful if that got
      rephrased as Z.
  validations:
    required: true

- type: input
  attributes:
    label: Component Name
    description: >
      Write the short name of the rst file or
      feature below, *use your best guess if unsure*.
    placeholder: docs/docsite/rst/dev_guide/debugging.rst
  validations:
    required: true

- type: textarea
  attributes:
    label: Ansible-navigator Version
    description: >-
      Paste verbatim output from `ansible-navigator --version` below, under
      the prompt line. Please don't wrap it with tripple backticks — your
      whole input will be turned into a code snippet automatically.
    render: console
    value: |
      $ ansible-navigator --version
    placeholder: |
      $ ansible-navigator --version
      ansible-navigator 0.7.0
  validations:
    required: true

- type: textarea
  attributes:
    label: OS / Environment
    description: >-
      Provide all relevant information below, e.g. OS version,
      browser, etc.
    placeholder: Fedora 33, Firefox etc.
