---
name: ✨ Feature request
description: Suggest an idea for this project

body:
- type: markdown
  attributes:
    value: >
      **Thank you for wanting to suggest a feature for ansible-navigator!**



      💡
      Before you go ahead with your request, please first consider if it
      would be useful for majority of the ansible-navigator users.


      <details>
        <summary>
          ❗ Every change breaks someone's workflow.
        </summary>


        [![❗ Every change breaks someone's workflow.
        ](https://imgs.xkcd.com/comics/workflow.png)
        ](https://xkcd.com/1172/)
      </details>


      ⚠
      Verify first that your idea is not [already requested on
      GitHub][issue search].

      Also test if the main branch does not already implement this.


      **Tip:** If you are seeking community support, please consider
      [starting a mailing list thread or chatting in IRC][ML||IRC].



      [contribute to collections]:
      https://docs.ansible.com/ansible-core/devel/community/contributing_maintained_collections.html?utm_medium=github&utm_source=issue_form--feature_request.yml

      [IRC meetings]:
        https://docs.ansible.com/ansible-core/devel/community/communication.html?utm_medium=github&utm_source=issue_form--feature_request.yml#irc-meetings

      [issue search]: ../search?q=is%3Aissue&type=issues

      [ML||IRC]:
      https://docs.ansible.com/ansible-core/devel/community/communication.html?utm_medium=github&utm_source=issue_form--feature_request.yml#mailing-list-information

      [new proposal]: ../../proposals/issues/new


- type: textarea
  attributes:
    label: Summary
    description: >
      Describe the new feature/improvement you would like briefly below.


      What's the problem this feature will solve?

      What are you trying to do, that you are unable to achieve
      with ansible-navigator as it currently stands?


      * Provide examples of real-world use cases that this would enable
      and how it solves the problem you described.

      * How do you solve this now?

      * Have you tried to work around the problem using other tools?

      * Could there be a different approach to solving this issue?

    placeholder: >-
      I am trying to do X with ansible-navigator from the main branch on GitHub and
      I think that implementing a feature Y would be very helpful for me and
      every other user of ansible-navigator because of Z.
  validations:
    required: true

- type: dropdown
  attributes:
    label: Issue Type
    description: >
      Please select the single available option in the drop-down.

      <details>
        <summary>
          <em>Why?</em>
        </summary>

        We would do it by ourselves but unfortunatelly, the curent
        edition of GitHub Issue Forms Alpha does not support this yet 🤷


        _We will make it easier in the future, once GitHub
        supports dropdown defaults. Promise!_

      </details>
    # FIXME: Once GitHub allows defining the default choice, update this
    options:
    - Feature Idea
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Information
    description: |
      Describe how the feature would be used, why it is needed and what it would solve.

      **HINT:** You can paste https://gist.github.com links for larger files.
    value: |
      <!--- Paste example playbooks or commands between quotes below -->
      ```yaml (paste below)

      ```
    placeholder: >-
      I asked on https://stackoverflow.com/.... and the community
      advised me to do X, Y and Z.
  validations:
    required: true


- type: markdown
  attributes:
    value: >
      *One last thing...*


      *Please, complete **all** sections as described, this form
      is [processed automatically by a robot][ansibot help].*


      Thank you for your collaboration!

- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [Ansible Code of Conduct][CoC] first.

      [CoC]: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_form--feature_request.yml
    options:
    - label: I agree to follow the Ansible Code of Conduct
      required: true
...
