"""Stub (interface) file for ``_version.py``.

Provides type hint PEP 484 information for the ``_version.py``
file because it is generated by setuptools_scm and may
not exist when type checking is don and will not
container type hint information.
"""

version: str
