- name: Summarize the execution environment details
  set_fact:
    summary:
      name: "{{ ee_image }}"
      ansible_version: "{{ ansible_version.full }}"
      base_os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
      collections: "{{ collections }}"
      python_packages: "{{ python_packages }}"
      python_version: "{{ ansible_python_version }}"
