 

  - hosts: execution-environment
    name: "Gather execution environment details for {{ ee_image }}"
    connection: local
    gather_facts: False
    tasks:
    - name: Gather execution environment details
      include_role:
        name: ansible.ansible_navigator.ee_details

  - hosts: execution-environment
    name: "Extract execution environment details for {{ ee_image }}"
    connection: local
    gather_facts: False
    tasks:
    - name: Extract execution environment details
      include_role:
        name: ansible.ansible_navigator.ee_report

  - hosts: execution-environment
    name: "Review execution environment details for {{ ee_image }}"
    connection: local
    gather_facts: False
    tasks:
    - name: "Review execution environment details"
      debug: 
        var: summary
    