---
- project:
    check:
      jobs:
        - ansible-navigator-tox-lint
        - ansible-navigator-tox-lint-vetting
        - ansible-navigator-tox-py36
        - ansible-navigator-tox-py37
        - ansible-navigator-tox-py38
        - ansible-navigator-tox-py39
        - ansible-navigator-tox-py310
        - ansible-navigator-tox-smoke
    gate:
      jobs:
        - ansible-navigator-tox-lint
        - ansible-navigator-tox-py36
        - ansible-navigator-tox-py37
        - ansible-navigator-tox-py38
        - ansible-navigator-tox-py39
        - ansible-navigator-tox-py310
        - ansible-navigator-tox-smoke
