---
- project:
    check:
      jobs:
        - ansible-navigator-tox-lint
        - ansible-navigator-tox-lint-vetting
        - ansible-navigator-tox-py38
        - ansible-navigator-tox-smoke
    gate:
      jobs:
        - ansible-navigator-tox-lint
        - ansible-navigator-tox-py38
        - ansible-navigator-tox-smoke
