---
name: tox

on:
  merge_group:
    branches:
      - "main"
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  checks: read
  contents: read
  id-token: write
  pull-requests: write

jobs:
  tox:
    uses: ansible/team-devtools/.github/workflows/tox.yml@main
    with:
      min_python: "3.12"
      max_python: "3.13"
      default_python: "3.12"
      other_names: |
        lint
        docs
        no-test-deps
      platforms: linux,macos
    secrets: inherit
